### ISSUE TITLE
请问使用的是哪个版本的OpenCV？

### ISSUE THREAD

**Issue by Innocent-children** [FlyAndNotDown/MazeGame#1]

**Comment by FlyAndNotDown** [comment]
几年前写的了，我自己也记不太清了，但看头文件里面写的应该是 opencv2，我印象中拿 opencv 只是为了读图片，如果实在匹配不上 opencv 版本你可以使用 stb_image 替代，这个库读文件很好用

**Comment by Innocent-children** [comment]
> 几年前写的了，我自己也记不太清了，但看头文件里面写的应该是 opencv2，我印象中拿 opencv 只是为了读图片，如果实在匹配不上 opencv 版本你可以使用 stb_image 替代，这个库读文件很好用

感谢回复

**Comment by FlyAndNotDown** [comment]
没事儿
